## CONFIGURATION FILE

# SIMULATION PARAMETERS
tEnd:                   120      # seconds   End time of the simulation
fIMU:                   100     # Hz        IMU and EKF rate
fGNSS:                  1       # Hz        GNSS rate
tDelay:                 0     # seconds   GNSS observations delay
# IMU SENSORS NOISE:
varAccNoise:            0.01    # m^2/s^3   Variance of the accelerometer
varAccBiasNoise:        0.001   # m^2/s^5   Variance of the accelerometer bias
varGyroNoise:           0.1       # deg^2/s   Variance of the gyroscope
varGyroBiasNoise:       0.001   # deg^2/s^3 Variance of the gyroscope bias
varDelayProcessNoise:   0       # s         Variance of process noise of the delay
# GNSS MEASUREMENT NOISE:
varPosGNSS:             1        # m^2      Variance of the GNSS position measurement

# TRUE TRAJECTORY DEFINITION
a0:                     0       # m/s^2     Initial acceleration
v0:                     1       # m/s       Initial velocity
pNorth0:                0       # m         Initial North position
pEast0:                 0       # m         Initial East position
headingRate0:           0       # deg/s     Initial angular velocity
heading0:               45      # deg       Initial heading

# LOOSELY COOPLED INTEGRATION:
# ERROR-STATE VECTOR INITIALIZATION
xErrpNorth0:               20      # m         Initial North position error
xErrpEast0:                20      # m         Initial East position error
xErrv0:                    10      # m/s       Initial velocity error 
xErrheading0:              45      # deg       Initial heading angle error
xErrba0:                   0       # m/s^2     Initial acceleration bias error
xErrbg0:                   0       # deg/s     Initial gyroscope bias error
xErrt0:                    0.02    # s         Initial time delay error
# COVARIANCE MATRIX INITIALIZATION
sigmaInitNorthPos:      0.5     # m         Initial STD of the North position error
sigmaInitEastPos:       0.5     # m         Initial STD of the East position error
sigmaInitVel:           2       # m/s       Initial STD of the velocity error
sigmaInitHeading:       3       # deg       Initial STD of the heading error
sigmaInitAccBias:       0.002   # m/s^2     Initial STD of the acceleration bias error
sigmaInitGyroBias:      0.002   # deg/s     Initial STD of the gyroscope bias error
sigmaInitDelay:         0.01    # s         Initial STD of the time delay error
