## CONFIGURATION FILE

# SIMULATION PARAMETERS
tEnd:           900     # seconds   End time of the simulation
fIMU:           100     # Hz        IMU and EKF rate
fGNSS:          1       # Hz        GNSS rate
tDelay:         0.505     # seconds   GNSS observations delay

# IMU SENSORS MEASUREMENT NOISE:
varMeasAcc:     0.01     # m^2/s^2   Variance of the accelerometer measurement
biasMeasAcc:    0.1    # m/s^2     Accelerometer bias
# GNSS MEASUREMENT NOISE:
varMeasPosGNSS: 100       # m^2      Variance of the GNSS position measurements

# TRUE TRAJECTORY DEFINITION
a0:             0    # m/s^2     Constant value of acceleration
aAmp:           5       # m/s^2     Amplitude of the sinusoidal    
aFreq:          0.01    # Hz        Frequency of the sinusoiidal variation of acceleration
v0:             15      # m/s       Initial velocity
p0:             0       # m         Initial position

# LOOSELY COOPLED INTEGRATION:
# GNSS/INS INTEGRATION NAVIGATION SOLUTION VECTOR INITIALIZATION
rp0:             0      # m         Initial position
rv0:             0      # m/s       Initial velocity 
rba0:            0      # m/s^2     Initial acceleration bias 
rt0:             0      # s         Initial time delay 

# LOOSELY COOPLED INTEGRATION:
# GNSS/INS INTEGRATION NAVIGATION SOLUTION VECTOR INITIALIZATION
xpNorth0:               1      # m         Initial North position
xpEast0:                1      # m         Initial East position
xv0:                    1       # m/s       Initial velocity error 
xheading0:              45      # deg       Initial heading angle
xba0:                   0       # m/s^2     Initial acceleration bias
xbg0:                   0       # deg/s     Initial gyroscope bias
xt0:                    0.02    # s         Initial time delay
# COVARIANCE MATRIX INITIALIZATION
sigmaInitPos:       0.4   # m         Initial STD of the position error
sigmaInitVel:       0.4   # m/s       Initial STD of the velocity error
sigmaInitAccBias:   0.2   # m/s^2     Initial STD of the accelerometer bias
sigmaInitDelay:     1   # s         Initial STD of the time delay error
# SYSTEM NOISE COVARIANCE MATRIX (Q)
varAccNoise:            0.01     # m^2/s^3   Variance of the accelerometer process noise
varAccBiasNoise:        1e-5     # m^2/s^5   Variance of the accelerometer bias process noise
varDelayNoise:          0        # s^2         Variance of the delay process noise
# MEASUREMENT NOISE COVARIANCE MATRIX (R)
varPosGNSS:             120       # m^2      Variance of the GNSS measurement model (R)
