## CONFIGURATION FILE

# SIMULATION PARAMETERS
tEnd:           240      # seconds   End time of the simulation
fIMU:           100     # Hz        IMU and EKF rate
fGNSS:          1       # Hz        GNSS rate
tDelay:         0     # seconds   GNSS observations delay
#
sigmaAcc:       0     # m/s^2     STD of the accelerometer
sigmaGNSS:      0       # m         STD of the GNSS module
# 
a0:             0       # m/s^2     Initial acceleration
v0:             1       # m/s       Initial velocity
p0:             0       # m         Initial position

# NAVIGATION SOLUTION VECTOR INITIALIZATION
rp0:             0      # m         Initial position
rv0:             1      # m/s       Initial velocity 
rba0:            0      # m/s^2     Initial acceleration bias 
rt0:             0  # s         Initial time delay 

# COVARIANCE MATRIX INITIALIZATION
sigmaPos:       0       # m         Initial STD of the position error
sigmaVel:       0       # m/s       Initial STD of the velocity error
sigmaAccBias:   0.0   # m/s^2     Initial STD of the acceleration bias error
sigmaTd:        0.0    # s         Initial STD of the time delay error
