## CONFIGURATION FILE

# SIMULATION PARAMETERS
tEnd:           240      # seconds   End time of the simulation
fIMU:           100     # Hz        IMU and EKF rate
fGNSS:          1       # Hz        GNSS rate
tDelay:         0.1  # seconds   GNSS observations delay

# IMU SENSORS MEASUREMENT NOISE:
varMeasAcc:     0.1     # m^2/s^2   Variance of the accelerometer measurement
biasMeasAcc:        0.1    # m/s^2     Accelerometer bias
# GNSS MEASUREMENT NOISE:
varMeasPosGNSS:         100       # m^2      Variance of the GNSS position measurements

# TRUE TRAJECTORY DEFINITION
a0:             0       # m/s^2     Initial acceleration
v0:             1       # m/s       Initial velocity
pNorth0:        0       # m         Initial North position
pEast0:         0       # m         Initial East position
psi0:           0.7854  # rad       Initial heading  

# LOOSELY COOPLED INTEGRATION:
# GNSS/INS INTEGRATION NAVIGATION SOLUTION VECTOR INITIALIZATION
rpNorth0:        0       # m         Initial North position
rpEast0:         0       # m         Initial East position
rv0:             1      # m/s       Initial velocity 
rpsi0:           0.7854  # rad       Initial heading
rba0:            0      # m/s^2     Initial acceleration bias 
rt0:             0      # s         Initial time delay 

# COVARIANCE MATRIX INITIALIZATION
sigmaInitNorthPos:  0.5     # m         Initial STD of the North position error
sigmaInitEastPos:   0.5     # m         Initial STD of the East position error
sigmaInitVel:       0.5   # m/s       Initial STD of the velocity error
sigmaInitHeading:   0.5     # rad       Initial STD of the heading error
sigmaInitAccBias:   0.5   # m/s^2     Initial STD of the accelerometer bias
sigmaInitDelay:     0.2   # s         Initial STD of the time delay error
# SYSTEM NOISE COVARIANCE MATRIX (Q)
varAccNoise:            0.01     # m^2/s^3   Variance of the accelerometer process noise
varAccBiasNoise:        1e-8     # m^2/s^5   Variance of the accelerometer bias process noise
varDelayNoise:          0.000001       # s         Variance of the delay process noise
# MEASUREMENT NOISE COVARIANCE MATRIX (R)
varPosGNSS:             100       # m^2      Variance of the GNSS measurement model (R)