function initColumns()

global COL_TRAJECTORY_TIME COL_TRAJECTORY_POS COL_TRAJECTORY_VEL COL_TRAJECTORY_ACC 

COL_TRAJECTORY_TIME = 1;
COL_TRAJECTORY_POS  = 2;
COL_TRAJECTORY_VEL  = 3; 
COL_TRAJECTORY_ACC  = 4;


end